from __future__ import annotations

from .normalization import canonical_entity, tokens
from .query_understanding import SearchPlan, clarification_for, understand
from .llm import OllamaQueryInterpreter
from .vector import SemanticVectorIndex
from .ranking import score_document
from .repository import SearchDocumentsRepository
from .typo import correct_tokens


class SearchService:
    MAX_RESULTS = 5

    def __init__(self, repository: SearchDocumentsRepository, fuzzy_threshold: int = 82):
        self.repository = repository
        self.fuzzy_threshold = fuzzy_threshold
        self._vocabulary: list[str] | None = None
        self.llm = OllamaQueryInterpreter()
        self.semantic = SemanticVectorIndex()

    def _get_vocabulary(self, query_tokens: list[str] | None = None) -> list[str]:
        # Vocabulary candidates are query-specific. Keeping a single vocabulary
        # generated by the first request would make later typo corrections
        # depend on unrelated traffic.
        values: set[str] = set(self._vocabulary or [])
        for token in query_tokens or []:
            try:
                values.update(self.repository.suggest_vocabulary(token))
            except AttributeError:
                pass
        self._vocabulary = sorted(values)
        return self._vocabulary

    def invalidate_vocabulary(self) -> None:
        self._vocabulary = None

    @staticmethod
    def _nested(doc: dict, *path: str):
        value = doc
        for key in path:
            if not isinstance(value, dict):
                return None
            value = value.get(key)
        return value

    @classmethod
    def _description(cls, doc: dict) -> str | None:
        for value in (
            doc.get("description"),
            doc.get("subtitle"),
            doc.get("sub_title"),
            doc.get("question"),
            doc.get("answer"),
            cls._nested(doc, "job", "description"),
            cls._nested(doc, "content", "text"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    @classmethod
    def _location(cls, doc: dict) -> dict:
        location = doc.get("location") if isinstance(doc.get("location"), dict) else {}
        country = location.get("country") if isinstance(location.get("country"), dict) else {}
        return {
            "city": location.get("city") or location.get("current_location") or location.get("prime_city"),
            "country": country.get("name") or country.get("ac_name") or country.get("code"),
            "address": location.get("address"),
        }

    @classmethod
    def _category(cls, doc: dict) -> str | None:
        category = doc.get("category")
        if isinstance(category, dict):
            return category.get("name")
        if isinstance(category, str):
            return category
        return None

    @classmethod
    def _url(cls, doc: dict) -> str | None:
        for value in (
            doc.get("url"),
            cls._nested(doc, "links", "detail"),
            doc.get("slug"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    @classmethod
    def _image(cls, doc: dict) -> str | None:
        for value in (
            doc.get("profile_image"),
            doc.get("cover_image"),
            cls._nested(doc, "media", "image"),
            cls._nested(doc, "media", "main_image", "path"),
            cls._nested(doc, "media", "banner"),
            cls._nested(doc, "media", "avatar"),
            cls._nested(doc, "user", "profile_image"),
            cls._nested(doc, "company", "avatar"),
            cls._nested(doc, "author", "avatar"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    @staticmethod
    def _result_payload(doc: dict, score: float, matched: list[str], corrected_query: str | None = None) -> dict:
        return {
            "entity_type": str(doc.get("entity_type") or ""),
            "entity_id": str(doc.get("source", {}).get("object_id") or doc.get("_id") or ""),
            "title": str(doc.get("title") or doc.get("question") or doc.get("short_title") or "Untitled result"),
            "description": SearchService._description(doc),
            "location": SearchService._location(doc),
            "category": SearchService._category(doc),
            "url": SearchService._url(doc),
            "image": SearchService._image(doc),
            "score": round(score, 4),
            "matched_by": list(dict.fromkeys(matched)),
            "corrected_query": corrected_query,
        }

    def _hard_filter_docs(
        cls,
        docs: list[dict],
        plan: SearchPlan,
        status: str | None,
        is_live: bool | None,
        structured: dict,
    ) -> list[dict]:
        """
        Final authoritative filter applied after every retrieval path.

        This is intentionally performed after lexical, fallback and semantic
        retrieval so no candidate can bypass explicit user constraints.
        """
        filtered = []

        for doc in docs:
            if not cls._document_matches_filters(
                doc,
                entity=plan.entity,
                city=plan.city,
                country=plan.country,
                status=status,
                is_live=is_live,
                structured=structured,
                date_from=plan.date_from,
                date_to=plan.date_to,
            ):
                continue

            filtered.append(doc)

        return filtered

    @classmethod
    def _document_matches_filters(
        cls,
        doc: dict,
        *,
        entity: str | None,
        city: str | None,
        country: str | None,
        status: str | None,
        is_live: bool | None,
        structured: dict | None = None,
        date_from=None,
        date_to=None,
    ) -> bool:
        """
        Delegate the authoritative document-level filter to the repository.
        """
        return cls._repository_document_matches_filters(
            doc,
            entity=entity,
            city=city,
            country=country,
            status=status,
            is_live=is_live,
            structured=structured,
            date_from=date_from,
            date_to=date_to,
        )

    @classmethod
    def _repository_document_matches_filters(
        cls,
        doc: dict,
        *,
        entity: str | None,
        city: str | None,
        country: str | None,
        status: str | None,
        is_live: bool | None,
        structured: dict | None = None,
        date_from=None,
        date_to=None,
    ) -> bool:
        return SearchDocumentsRepository._document_matches_filters(
            doc,
            entity=entity,
            city=city,
            country=country,
            status=status,
            is_live=is_live,
            structured=structured,
            date_from=date_from,
            date_to=date_to,
        )

    def search(
        self,
        *,
        query: str,
        entity: str | None = None,
        city: str | None = None,
        country: str | None = None,
        status: str | None = None,
        is_live: bool | None = None,
        limit: int = 5,
    ) -> dict:
        original = " ".join(query.strip().split())
        if not original:
            return {"query": original, "corrected_query": None, "total": 0, "results": []}

        # Phase 2: deterministic natural-language understanding first.
        plan = understand(original)
        if entity:
            plan.entity = canonical_entity(entity)
        if city:
            plan.city = city
        if country:
            plan.country = country

        # Ollama is a fallback, not the default path. Simple/clear searches
        # never need an LLM request.
        deterministic_plan = understand(original)

        if plan.confidence < 0.65 or (plan.entity and not plan.keywords and not plan.category):
            plan = self.llm.interpret(original, plan)

        # Deterministic entity/location/filter extraction is authoritative.
        # The LLM may fill genuinely ambiguous fields but cannot erase a clear
        # module/entity decision such as "find senior chefs in Dubai".
        if deterministic_plan.entity:
            plan.entity = deterministic_plan.entity
        if deterministic_plan.city:
            plan.city = deterministic_plan.city
        if deterministic_plan.country:
            plan.country = deterministic_plan.country
        if deterministic_plan.experience is not None:
            plan.experience = deterministic_plan.experience
        if deterministic_plan.level:
            plan.level = deterministic_plan.level
        if deterministic_plan.department:
            plan.department = deterministic_plan.department
        if deterministic_plan.industry:
            plan.industry = deterministic_plan.industry
        if deterministic_plan.category:
            plan.category = deterministic_plan.category
        plan.filters = dict(deterministic_plan.filters)
        plan.date_from, plan.date_to = deterministic_plan.date_from, deterministic_plan.date_to

        clarification = clarification_for(plan)
        understanding = plan.as_dict()
        understanding["clarification"] = clarification

        if clarification:
            return {
                "query": original,
                "corrected_query": None,
                "total": 0,
                "results": [],
                "understanding": understanding,
            }

        search_tokens = plan.keywords or tokens(original)
        if not search_tokens:
            return {
                "query": original,
                "corrected_query": None,
                "total": 0,
                "results": [],
                "understanding": understanding,
            }

        # Typo correction applies to the actual search terms, not control words
        # such as "jobs", "in", "Dubai", etc.
        vocabulary = self._get_vocabulary(search_tokens)
        corrected_tokens, changes = correct_tokens(
            search_tokens,
            vocabulary,
            threshold=self.fuzzy_threshold,
        )
        corrected_query = " ".join(corrected_tokens).strip()
        effective_query = corrected_query or " ".join(search_tokens)

        # Include extracted structured concepts in lexical retrieval as well.
        # This is important when the Mongo document stores these concepts in
        # ai_search_text but does not expose them through a uniform structured
        # field (job/professional schemas differ).
        retrieval_terms = list(search_tokens)
        for value in (plan.level, plan.department, plan.industry, plan.category):
            if value:
                retrieval_terms.extend(tokens(str(value)))
        retrieval_terms = list(dict.fromkeys(retrieval_terms))
        retrieval_query = " ".join(retrieval_terms).strip() or effective_query

        # Explicit API filters override extracted natural-language filters.
        canonical_entity_name = canonical_entity(plan.entity)
        if canonical_entity_name in {
            "job", "professional", "company", "product",
            "article", "event", "award", "faq",
        }:
            plan.entity = canonical_entity_name

        structured = dict(plan.filters)
        if plan.experience is not None:
            structured["experience"] = plan.experience
        if plan.level:
            structured["level"] = plan.level
        if plan.department:
            structured["department"] = plan.department
        if plan.industry:
            structured["industry"] = plan.industry
        if plan.category:
            structured["category"] = plan.category

        limit = min(max(int(limit), 1), self.MAX_RESULTS)
        docs = self.repository.search(
            retrieval_query,
            entity=plan.entity,
            city=plan.city,
            country=plan.country,
            status=status,
            is_live=is_live,
            limit=100,
            structured=structured,
            date_from=plan.date_from,
            date_to=plan.date_to,
        )

        # Structured fields are not uniform across all search_documents
        # entities. If a strict structured query produces no candidates, retry
        # using the authoritative entity/location/status filters and let the
        # lexical ranking terms above represent the softer concepts. This
        # prevents a missing/non-standard job experience field from turning a
        # valid natural-language search into zero results.
        if not docs and structured:
            docs = self.repository.search(
                retrieval_query,
                entity=plan.entity,
                city=plan.city,
                country=plan.country,
                status=status,
                is_live=is_live,
                limit=100,
                structured={},
                date_from=plan.date_from,
                date_to=plan.date_to,
            )

        semantic_scores = {}
        for doc_id, semantic_score in self.semantic.search(effective_query, limit=50):
            semantic_scores[doc_id] = semantic_score
        if semantic_scores:
            semantic_docs = self.repository.fetch_by_ids(list(semantic_scores))
            semantic_docs = [
                d for d in semantic_docs
                if self.repository._document_matches_filters(
                    d,
                    entity=plan.entity,
                    city=plan.city,
                    country=plan.country,
                    status=status,
                    is_live=is_live,
                    structured=structured,
                    date_from=plan.date_from,
                    date_to=plan.date_to,
                )
            ]
            seen = {str(d.get("_id")) for d in docs}
            docs.extend(d for d in semantic_docs if str(d.get("_id")) not in seen)

        # If a typo correction occurred, search the original keyword phrase too
        # so correction can never hide an exact MongoDB match.
        if changes and corrected_query != " ".join(search_tokens):
            original_query = " ".join(search_tokens)
            original_docs = self.repository.search(
                original_query,
                entity=plan.entity,
                city=plan.city,
                country=plan.country,
                status=status,
                is_live=is_live,
                limit=100,
                structured=structured,
                date_from=plan.date_from,
                date_to=plan.date_to,
            )
            seen = {str(d.get("_id")) for d in docs}
            docs.extend(d for d in original_docs if str(d.get("_id")) not in seen)

        # Final authoritative guard: every candidate source (lexical,
        # semantic, fallback) must satisfy the same hard constraints.
        docs = self._hard_filter_docs(docs, plan, status, is_live, structured)

        related_docs: list[dict] = []
        related_label = None
        # Exact constraints are authoritative. If they produce no candidates,
        # do a separate relaxed search for helpful alternatives rather than
        # silently returning wrong-location documents as exact matches.
        if not docs and (plan.city or plan.country or structured):
            related_docs = self.repository.search(
                effective_query,
                entity=plan.entity,
                city=None,
                country=None,
                status=status,
                is_live=is_live,
                limit=50,
                structured={},
                date_from=plan.date_from,
                date_to=plan.date_to,
            )
            if related_docs:
                related_label = "We couldn't find an exact match for your requested filters. Here are related results you can check below."

        ranked = []
        for doc in docs:
            score, matched = score_document(
                doc,
                retrieval_query,
                float(doc.get("text_score") or 0.0),
            )
            semantic_score = semantic_scores.get(str(doc.get("_id")))
            if semantic_score is not None:
                score += max(0.0, semantic_score) * 35.0
                matched.append("semantic")
            # Small, deterministic boosts for structured constraints. These
            # never override exact lexical identity, but help tie-break natural
            # language searches.
            if plan.city or plan.country:
                matched.append("location_filter")
                score += 12
            if plan.level or plan.department or plan.industry or plan.experience is not None:
                matched.append("structured_filter")
                score += 8
            if plan.category:
                matched.append("category_filter")
                score += 5
            if plan.date_from or plan.date_to:
                matched.append("date_filter")
                score += 3
            ranked.append((score, doc, matched))

        ranked.sort(key=lambda item: (-item[0], str(item[1].get("_id"))))

        results = [
            self._result_payload(doc, score, matched, corrected_query if changes else None)
            for score, doc, matched in ranked[:limit]
        ]

        related_results = []
        if not results and related_docs:
            related_ranked = []
            for doc in related_docs:
                score, matched = score_document(
                    doc,
                    retrieval_query,
                    float(doc.get("text_score") or 0.0),
                )
                # Related results are explicitly marked as such; their score
                # must never leak into the exact-result ranking.
                matched = list(dict.fromkeys(matched + ["related_result"]))
                related_ranked.append((score, doc, matched))
            related_ranked.sort(key=lambda item: (-item[0], str(item[1].get("_id"))))
            related_results = [
                self._result_payload(doc, score, matched, corrected_query if changes else None)
                for score, doc, matched in related_ranked[:limit]
            ]

        understanding["keywords"] = search_tokens
        understanding["corrected_keywords"] = corrected_tokens
        understanding["corrections"] = changes

        return {
            "query": original,
            "corrected_query": corrected_query if changes else None,
            "total": len(results),
            "results": results,
            "message": related_label,
            "related_results": related_results,
            "understanding": understanding,
        }

