from __future__ import annotations

from .normalization import canonical_entity, tokens
from .query_understanding import SearchPlan, clarification_for, understand
from .llm import GeminiQueryInterpreter
from .vector import SemanticVectorIndex
from .ranking import score_document
from .repository import SearchDocumentsRepository
from .typo import correct_tokens


class SearchService:
    MAX_RESULTS = 5

    def __init__(self, repository: SearchDocumentsRepository, fuzzy_threshold: int = 82):
        self.repository = repository
        self.fuzzy_threshold = fuzzy_threshold
        self._vocabulary: list[str] | None = None
        self.llm = GeminiQueryInterpreter()
        self.semantic = SemanticVectorIndex()

    def _get_vocabulary(self, query_tokens: list[str] | None = None) -> list[str]:
        # Vocabulary candidates are query-specific. Keeping a single vocabulary
        # generated by the first request would make later typo corrections
        # depend on unrelated traffic.
        values: set[str] = set(self._vocabulary or [])
        for token in query_tokens or []:
            try:
                values.update(self.repository.suggest_vocabulary(token))
            except AttributeError:
                pass
        self._vocabulary = sorted(values)
        return self._vocabulary

    def invalidate_vocabulary(self) -> None:
        self._vocabulary = None

    @staticmethod
    def _nested(doc: dict, *path: str):
        value = doc
        for key in path:
            if not isinstance(value, dict):
                return None
            value = value.get(key)
        return value

    @classmethod
    def _description(cls, doc: dict) -> str | None:
        for value in (
            doc.get("description"),
            doc.get("subtitle"),
            doc.get("sub_title"),
            doc.get("question"),
            doc.get("answer"),
            cls._nested(doc, "job", "description"),
            cls._nested(doc, "content", "text"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    @classmethod
    def _location(cls, doc: dict) -> dict:
        location = doc.get("location") if isinstance(doc.get("location"), dict) else {}
        country = location.get("country") if isinstance(location.get("country"), dict) else {}
        return {
            "city": location.get("city") or location.get("current_location") or location.get("prime_city"),
            "country": country.get("name") or country.get("ac_name") or country.get("code"),
            "address": location.get("address"),
        }

    @classmethod
    def _category(cls, doc: dict) -> str | None:
        category = doc.get("category")
        if isinstance(category, dict):
            return category.get("name")
        if isinstance(category, str):
            return category
        return None

    @classmethod
    def _url(cls, doc: dict) -> str | None:
        for value in (
            doc.get("url"),
            cls._nested(doc, "links", "detail"),
            doc.get("slug"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    @classmethod
    def _image(cls, doc: dict) -> str | None:
        for value in (
            doc.get("profile_image"),
            doc.get("cover_image"),
            cls._nested(doc, "media", "image"),
            cls._nested(doc, "media", "main_image", "path"),
            cls._nested(doc, "media", "banner"),
            cls._nested(doc, "media", "avatar"),
            cls._nested(doc, "user", "profile_image"),
            cls._nested(doc, "company", "avatar"),
            cls._nested(doc, "author", "avatar"),
        ):
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None

    def search(
        self,
        *,
        query: str,
        entity: str | None = None,
        city: str | None = None,
        country: str | None = None,
        status: str | None = None,
        is_live: bool | None = None,
        limit: int = 5,
    ) -> dict:
        original = " ".join(query.strip().split())
        if not original:
            return {"query": original, "corrected_query": None, "total": 0, "results": []}

        # Phase 2: deterministic natural-language understanding first.
        plan = understand(original)
        if entity:
            plan.entity = canonical_entity(entity)
        if city:
            plan.city = city
        if country:
            plan.country = country

        # The LLM is a fallback, not the default path. Simple/clear searches
        # never need a Gemini request.
        if plan.confidence < 0.65 or (plan.entity and not plan.keywords and not plan.category):
            plan = self.llm.interpret(original, plan)

        clarification = clarification_for(plan)
        understanding = plan.as_dict()
        understanding["clarification"] = clarification

        if clarification:
            return {
                "query": original,
                "corrected_query": None,
                "total": 0,
                "results": [],
                "understanding": understanding,
            }

        search_tokens = plan.keywords or tokens(original)
        if not search_tokens:
            return {
                "query": original,
                "corrected_query": None,
                "total": 0,
                "results": [],
                "understanding": understanding,
            }

        # Typo correction applies to the actual search terms, not control words
        # such as "jobs", "in", "Dubai", etc.
        vocabulary = self._get_vocabulary(search_tokens)
        corrected_tokens, changes = correct_tokens(
            search_tokens,
            vocabulary,
            threshold=self.fuzzy_threshold,
        )
        corrected_query = " ".join(corrected_tokens).strip()
        effective_query = corrected_query or " ".join(search_tokens)

        # Explicit API filters override extracted natural-language filters.
        canonical_entity_name = canonical_entity(plan.entity)
        if canonical_entity_name in {
            "job", "professional", "company", "product",
            "article", "event", "award", "faq",
        }:
            plan.entity = canonical_entity_name

        structured = dict(plan.filters)
        if plan.experience is not None:
            structured["experience"] = plan.experience
        if plan.level:
            structured["level"] = plan.level
        if plan.department:
            structured["department"] = plan.department
        if plan.industry:
            structured["industry"] = plan.industry
        if plan.category:
            structured["category"] = plan.category

        limit = min(max(int(limit), 1), self.MAX_RESULTS)
        docs = self.repository.search(
            effective_query,
            entity=plan.entity,
            city=plan.city,
            country=plan.country,
            status=status,
            is_live=is_live,
            limit=100,
            structured=structured,
            date_from=plan.date_from,
            date_to=plan.date_to,
        )

        semantic_scores = {}
        for doc_id, semantic_score in self.semantic.search(effective_query, limit=50):
            semantic_scores[doc_id] = semantic_score
        if semantic_scores:
            semantic_docs = self.repository.fetch_by_ids(list(semantic_scores))
            seen = {str(d.get("_id")) for d in docs}
            docs.extend(d for d in semantic_docs if str(d.get("_id")) not in seen)

        # If a typo correction occurred, search the original keyword phrase too
        # so correction can never hide an exact MongoDB match.
        if changes and corrected_query != " ".join(search_tokens):
            original_query = " ".join(search_tokens)
            original_docs = self.repository.search(
                original_query,
                entity=plan.entity,
                city=plan.city,
                country=plan.country,
                status=status,
                is_live=is_live,
                limit=100,
                structured=structured,
                date_from=plan.date_from,
                date_to=plan.date_to,
            )
            seen = {str(d.get("_id")) for d in docs}
            docs.extend(d for d in original_docs if str(d.get("_id")) not in seen)

        ranked = []
        for doc in docs:
            score, matched = score_document(
                doc,
                effective_query,
                float(doc.get("text_score") or 0.0),
            )
            semantic_score = semantic_scores.get(str(doc.get("_id")))
            if semantic_score is not None:
                score += max(0.0, semantic_score) * 35.0
                matched.append("semantic")
            # Small, deterministic boosts for structured constraints. These
            # never override exact lexical identity, but help tie-break natural
            # language searches.
            if plan.city or plan.country:
                matched.append("location_filter")
                score += 12
            if plan.level or plan.department or plan.industry or plan.experience is not None:
                matched.append("structured_filter")
                score += 8
            if plan.category:
                matched.append("category_filter")
                score += 5
            if plan.date_from or plan.date_to:
                matched.append("date_filter")
                score += 3
            ranked.append((score, doc, matched))

        ranked.sort(key=lambda item: (-item[0], str(item[1].get("_id"))))

        results = []
        for score, doc, matched in ranked[:limit]:
            results.append({
                "entity_type": str(doc.get("entity_type") or ""),
                "entity_id": str(doc.get("source", {}).get("object_id") or doc.get("_id") or ""),
                "title": str(doc.get("title") or doc.get("question") or doc.get("short_title") or "Untitled result"),
                "description": self._description(doc),
                "location": self._location(doc),
                "category": self._category(doc),
                "url": self._url(doc),
                "image": self._image(doc),
                "score": round(score, 4),
                "matched_by": list(dict.fromkeys(matched)),
                "corrected_query": corrected_query if changes else None,
            })

        understanding["keywords"] = search_tokens
        understanding["corrected_keywords"] = corrected_tokens
        understanding["corrections"] = changes

        return {
            "query": original,
            "corrected_query": corrected_query if changes else None,
            "total": len(results),
            "results": results,
            "understanding": understanding,
        }

